# Configuration de l'application Fly.io
app = "yugioh-s-card-imzc6g"  # Remplace par ton nom d'app Fly.io
primary_region = "mad"

[build]

[deploy]
  strategy = "rolling"

[processes]
  app = "python monbot.py"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
