# fly.toml app configuration file generated for yugioh-s-card-imzc6g on 2025-02-09T09:06:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yugioh-s-card-imzc6g'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
